from __future__ import annotations

from pathlib import Path

HEADER_PREFIX = "# Generated by omarchy-theme-targets."
HEADER = "\n".join((
    HEADER_PREFIX,
    "# Safe to replace or remove with `omarchy-theme-targets rollback`.",
    "",
))


def has_generated_header(path: Path) -> bool:
    try:
        return path.read_text(encoding="utf-8", errors="replace").startswith(HEADER_PREFIX)
    except OSError:
        return False


def classify_path(path: Path) -> str:
    if not path.exists():
        return "missing"
    if path.is_dir():
        return "error"
    if has_generated_header(path):
        return "applied"
    return "manual"


def can_write_generated(path: Path) -> tuple[bool, str | None]:
    if path.exists() and not has_generated_header(path):
        return False, "refusing to overwrite file without omarchy-theme-targets header"
    parent = path.parent
    if parent.exists() and not parent.is_dir():
        return False, f"output parent is not a directory: {parent}"
    if parent.exists():
        try:
            parent_stat = parent.stat()
            home_stat = Path.home().stat()
            if parent_stat.st_uid not in (home_stat.st_uid, 0):
                return False, f"unsafe output ownership for {parent}"
        except OSError as exc:
            return False, f"cannot stat output parent {parent}: {exc}"
    return True, None


def write_generated(path: Path, body: str, dry_run: bool = False) -> tuple[str, str]:
    allowed, reason = can_write_generated(path)
    if not allowed:
        return "manual", reason or "unsafe output"
    if dry_run:
        return "skipped", f"would write {path}"
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(HEADER + body, encoding="utf-8")
    except OSError as exc:
        return "error", f"failed to write {path}: {exc}"
    return "applied", f"wrote {path}"


def remove_generated(path: Path, dry_run: bool = False) -> tuple[str, str]:
    if not path.exists():
        return "skipped", f"not present: {path}"
    if not has_generated_header(path):
        return "manual", f"refusing to remove file without omarchy-theme-targets header: {path}"
    if dry_run:
        return "skipped", f"would remove {path}"
    try:
        path.unlink()
    except OSError as exc:
        return "error", f"failed to remove {path}: {exc}"
    return "applied", f"removed {path}"
